# Generated by Django 5.2.14 on 2026-05-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='category',
            field=models.CharField(choices=[('FOUNDATION', 'FOUNDATION'), ('TACTICAL', 'TACTICAL'), ('OPERATIONS', 'OPERATIONS'), ('LEGAL', 'LEGAL')], default='FOUNDATION', max_length=32),
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
